# Generated by Django 6.0.6 on 2026-06-13 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expense_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='monthly_limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
